### ISSUE TITLE
delete article from bill

### ISSUE THREAD

**Issue by DevUnderConstruction** [DevUnderConstruction/userStories#10]
## Value Proposition

**As a user** 

**I need to remove the article from bill**

**to be able to update it**

## Description

<img width="270" alt="US#9" src="https://user-images.githubusercontent.com/115790027/213121079-3f93fac9-de22-4951-8946-ead210e3a1e2.png">

## Acceptance Criteria

- [ ] on click minus the article should be removed from bill

## Tasks

(for developers team)

- [ ] create function which checks if article count is above 0
- [ ] remove article from bill if article count will be 0
