### ISSUE TITLE
Add and edit User-data

### ISSUE THREAD

**Issue by DevUnderConstruction** [DevUnderConstruction/userStories#3]
## Value Proposition

**As a user**

**I want to create my  Output billing address**

**I need to be able to edit if there are changes or mistakes.** 

## Description

![US#2](https://user-images.githubusercontent.com/115790027/207092057-58373294-64bf-4aa0-83b8-6469e027111f.png)

## Acceptance Criteria

- [ ] the form with inputs should be shown after pushing a button
- [ ] the full address has to be shown  
- [ ] complete first- and last,-name has to be shown 
- [ ] complete address has to be shown    
- [ ] all inputs have to be required
- [ ] edited user-data  has to be stored

## Tasks

(for developers team)

- [ ] create an Footer with navigation Button
- [ ] create an form Element
- [ ] create the inputs
- [ ] create an list item which shows short user data on the Startscreen

**Comment by WalterRestifo** [comment]
Great Work! Approved
