### ISSUE TITLE
Add customer

### ISSUE THREAD

**Issue by DevUnderConstruction** [DevUnderConstruction/userStories#4]
## Value Proposition

**As a user**

**I need to add costumers personal data**

**to be able to send bills**

## Description

<img width="509" alt="US#3" src="https://user-images.githubusercontent.com/115790027/207268605-1787fa57-9bf6-42e5-b835-a84a9205b2aa.png">

## Acceptance Criteria

- [ ] All Inputs are required.
- [ ] An costumer Id should been added automatically and increased by 1 for every new Costumer
- [ ] Inputs: First, - Lastname, email, full address, costumer id, tel

## Tasks

(for developers team)

- [ ] create an Button which navigates to the costumer form
- [ ] create necessary inputs
- [ ] create an an array with fake dummy costumer data

**Comment by WalterRestifo** [comment]
You rock!
