### ISSUE TITLE
Add ArticleForm

### ISSUE THREAD

**Issue by DevUnderConstruction** [DevUnderConstruction/userStories#5]
## Value Proposition

**As a user** ...(user, Author, logged in User...)

**I need to create new Articles and edit old ones**

**to be able to add them to my bill**

## Description

![US#4](https://user-images.githubusercontent.com/115790027/207903322-d1ca8b5d-18dc-4141-b508-e6887f7f0165.png)

## Acceptance Criteria

- [ ] the form with inputs should be shown after pushing a button
- [ ] edited article-data has to be stored
- [ ] all inputs have to be required
- [ ] complete Article data has tu be shown

## Tasks

(for developers team)

- [ ] create an Button which navigates to the article form
- [ ] create necessary inputs
- [ ] create an an array with fake dummy article data

**Comment by MerleMak** [comment]
Whenever the is and "and" in your Value proposition, it can definitely be two user stories :)
I would suggest you can do one US with adding new articles and another one with editing existing articles :)

**Comment by DevUnderConstruction** [comment]
Ok.

**Comment by DevUnderConstruction** [comment]
Bekomme ich noch einen Haken?
