### ISSUE TITLE
Edit articles

### ISSUE THREAD

**Issue by DevUnderConstruction** [DevUnderConstruction/userStories#6]
## Value Proposition

**As a user**

**I need to edit articles data**

**to be able to  set new prices or change the Name**

## Description

<img width="334" alt="US#5" src="https://user-images.githubusercontent.com/115790027/208073510-c31660ac-6c78-40c0-a220-7032ac80d79e.png">

## Acceptance Criteria

- [ ] edited article-data has to be stored
- [ ] all inputs have to be required
- [ ] complete Article data has tu be shown

## Tasks

(for developers team)

- [ ] create an search-bar to select article which should be edited
- [ ] show editable article data
- [ ] work with an array of fake dummy article data

**Comment by Hirnstromwelle** [comment]
Hey Jonas, es wäre vielleicht besser, die Story  aufzuteilen. Navigation separat und Inputfelder. Die Entscheidung liegt aber bei dir. : )
 
Und wo tauchen die Daten auf, wenn sie eingegeben wurden? Ansonsten find ich das alles super. Coole Zeichnung. : )

**Comment by DevUnderConstruction** [comment]
Danke für dein Feedback @Hirnstromwelle. Die Input Felder sind aus der vorherigen US und die Daten lasse ich im Input Feld selbst anzeigen
