### ISSUE TITLE
Select Customer

### ISSUE THREAD

**Issue by DevUnderConstruction** [DevUnderConstruction/userStories#7]
## Value Proposition

**As a user** 

**I need to select an customer**

**to be able to add the customer address on to the bill** 

## Description

<img width="399" alt="US#6" src="https://user-images.githubusercontent.com/115790027/211404484-e25ea035-b7b8-43ab-80e4-3eef28bb437d.png">

## Acceptance Criteria

- [ ] The click on the accountfield must lead to the select Customer inputfield
- [ ]  By clicking on the selectfield an list of customers has to be shown
- [ ] An customer has to be selected befor passing by 

## Tasks

(for developers team)

- [ ] create an onclick event to the accountfield
- [ ] create an dropdown list where the user could select from an list of all stored customers
- [ ] create an button where the user could confirm his choice

**Comment by julialoeschel** [comment]
lgtm 👀
