### ISSUE TITLE
Select articels

### ISSUE THREAD

**Issue by DevUnderConstruction** [DevUnderConstruction/userStories#8]
## Value Proposition

**As a user** 

**I need to select articles** ...(describe the goal)

**to be able to add them to the bill**

## Description

Scribble / design or text

## Acceptance Criteria

- [ ] The click on the confirm costumer button must lead to the Billcard
- [ ] 
- [ ] ...

## Tasks

(for developers team)

- [ ] list the tasks that need to be performend within the dev team
- [ ] e.g. Components, Storybook, testing
- [ ] ...

**Comment by julialoeschel** [comment]
great 🐜 
in the scribbel i am missing the save button (is it the red one? but I guess its the select approval)  and , once you touch the scribbel, try to add real adress data in your header to see proportions. 

besides this small things, very good story.
